
spring:
  datasource:
    dynamic:
      primary: busidb
      datasource:
        busidb:
          # JDBC 配置(驱动类自动从url的mysql识别,数据源类型自动识别)
          url: jdbc:mysql://localhost:3306/auth2024?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
          username: root
          password: fe92OEP0f1
          driver-class-name: com.mysql.cj.jdbc.Driver
        spss:
          url: jdbc:mysql://localhost:3306/authSpss?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
          username: root
          password: fe92OEP0f1
          driver-class-name: com.mysql.cj.jdbc.Driver
        notice:
          url: jdbc:mysql://localhost:3306/auth2025?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
          username: root
          password: fe92OEP0f1
          driver-class-name: com.mysql.cj.jdbc.Driver
        bak:
          url: jdbc:mysql://localhost:3306/auth2026?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
          username: root
          password: fe92OEP0f1
          driver-class-name: com.mysql.cj.jdbc.Driver
#

