CREATE TABLE `t_ocr_record` (
                                `ocrRecordId` bigint(20) NOT NULL COMMENT '主键Id',
                                `equipmentId` bigint(20) DEFAULT NULL COMMENT '设备硬件ID',
                                `hardCode` char(36) DEFAULT NULL COMMENT '设备硬件码',
                                `berthId` bigint(20) DEFAULT NULL COMMENT '泊位ID',
                                `berthCode` varchar(50) DEFAULT NULL COMMENT '泊位编码',
                                `parkId` bigint(20) NOT NULL COMMENT '车场ID',
                                `parkCode` varchar(50) NOT NULL COMMENT '车场编码',
                                `plateNumber` varchar(20) NOT NULL COMMENT '车牌号',
                                `carId` bigint(20) NOT NULL DEFAULT '0' COMMENT '车辆ID',
                                `lastCarId` bigint(20) NOT NULL,
                                `captureTime` bigint(20) NOT NULL COMMENT '图片抓拍时间',
                                `type` tinyint(1) DEFAULT NULL COMMENT '1=入场，0=出场',
                                `carType` tinyint(1) DEFAULT '0' COMMENT '车辆类型1=小，2=中，3=大',
                                `plateColor` tinyint(1) DEFAULT NULL COMMENT '车牌颜色',
                                `dataSource` tinyint(1) NOT NULL COMMENT '数据来源:',
                                `oprNum` varchar(40) NOT NULL COMMENT '流水号',
                                `entryOprNum` varchar(40) DEFAULT NULL COMMENT '入场流水号',
                                `lastBerthCode` varchar(50) DEFAULT NULL COMMENT '修改后的泊位',
                                `lastPlateNumber` varchar(15) NOT NULL COMMENT '修改后的车牌',
                                `lastType` tinyint(1) DEFAULT NULL COMMENT '修改后的出入场类型',
                                `eventReliability` int(11) DEFAULT '0' COMMENT '出入场置信度',
                                `plateReliability` int(11) DEFAULT '0' COMMENT '车牌置信度',
                                `width` int(11) DEFAULT '0' COMMENT '宽度',
                                `height` int(11) DEFAULT '0' COMMENT '高度',
                                `xAxis` int(11) DEFAULT '0' COMMENT 'x轴',
                                `yAxis` int(11) DEFAULT '0' COMMENT 'y轴',
                                `pdaManagerId` bigint(20) DEFAULT '0' COMMENT '操作收费员Id',
                                `createdTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                `updatedTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '时间戳',
                                `D` tinyint(1) DEFAULT '0' COMMENT '0:正常，1：删除',
                                `dataSourceDetail` tinyint(1) DEFAULT NULL,
                                `dataVersion` bigint(20) NOT NULL DEFAULT '0',
                                PRIMARY KEY (`ocrRecordId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='路侧车位上报记录表\r\n';


CREATE TABLE `t_park_record` (
                                 `parkRecordId` bigint(20) NOT NULL COMMENT 'ID',
                                 `recordCode` varchar(36) DEFAULT NULL COMMENT '停车记录编码',
                                 `recordState` tinyint(1) NOT NULL DEFAULT '1' COMMENT '状态，0：离场，1：在场，2：出场未识别 3:删除',
                                 `hardCode` varchar(36) DEFAULT NULL COMMENT '设备编码',
                                 `entryId` bigint(20) DEFAULT NULL COMMENT '入场流水Id',
                                 `entryOprNum` varchar(36) DEFAULT NULL,
                                 `exitId` bigint(20) DEFAULT NULL COMMENT '出场流水Id',
                                 `exitOprNum` varchar(36) DEFAULT NULL,
                                 `entryDataSource` tinyint(4) NOT NULL COMMENT '停车数据来源',
                                 `exitDataSource` tinyint(4) DEFAULT NULL COMMENT '停车数据来源',
                                 `entryTime` bigint(20) NOT NULL COMMENT '入场时间',
                                 `exitTime` bigint(20) DEFAULT NULL COMMENT '出场时间',
                                 `parkId` bigint(20) NOT NULL COMMENT '停车场ID',
                                 `parkCode` varchar(36) DEFAULT NULL COMMENT '停车场编码',
                                 `berthId` bigint(20) DEFAULT NULL COMMENT '泊位ID',
                                 `berthCode` varchar(36) DEFAULT NULL COMMENT '泊位编码',
                                 `carId` bigint(20) DEFAULT '0' COMMENT '车辆ID',
                                 `plateNumber` varchar(20) NOT NULL COMMENT '车牌号',
                                 `illegal` tinyint(1) DEFAULT '0' COMMENT '是否违章 0 否 1是',
                                 `createdTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                 `updatedTime` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '修改时间',
                                 `display` tinyint(4) DEFAULT NULL,
                                 `exception` int(11) NOT NULL DEFAULT '0' COMMENT '0 正常数据 1异常数据',
                                 `dataVersion` bigint(20) NOT NULL DEFAULT '0',
                                 PRIMARY KEY (`parkRecordId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='停车记录表';